from flask import Flask, request, jsonify
from flask_cors import CORS
from datetime import datetime
import uuid
import json
import os

app = Flask(__name__)
CORS(app)

# Simple in-memory database for demo (replace with Firebase RTDB connection)
resumes_db = {}

# Firebase RTDB REST API configuration
FIREBASE_RTDB_URL = "https://ai-resume-builder-b5dfc-default-rtdb.firebaseio.com"
FIREBASE_API_KEY = "your-api-key-here"  # You'll need to get this from Firebase Console

def generate_resume_text(data, template_type):
    """Generate resume text based on template type"""
    name = data.get('name', 'Your Name')
    email = data.get('email', 'your.email@example.com')
    phone = data.get('phone', 'Your Phone Number')
    education = data.get('education', 'Your Education')
    experience = data.get('experience', 'Your Work Experience')
    skills = data.get('skills', 'Your Skills')
    objective = data.get('objective', 'Your Career Objective')
    
    currentDate = datetime.now().strftime('%Y-%m-%d')
    
    if template_type == 'modern':
        return f"""┌─────────────────────────────────────────┐
│              {name.upper()}               │
└─────────────────────────────────────────┘

📊 {email} • {phone} • {currentDate}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💡 PROFESSIONAL SUMMARY
{objective}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🎯 CORE COMPETENCIES
{skills}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🚀 PROFESSIONAL EXPERIENCE
{experience}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📚 ACADEMIC BACKGROUND
{education}

Modern Resume Template • {currentDate}"""
    elif template_type == 'executive':
        return f"""╔════════════════════════════════════════╗
║         EXECUTIVE LEADERSHIP PROFILE        ║
╚════════════════════════════════════════╝

{name.upper()}
Executive Professional
{email} • {phone} • {currentDate}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🌟 EXECUTIVE SUMMARY
{objective}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💼 LEADERSHIP EXPERIENCE
{experience}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🎓 EDUCATION & CERTIFICATIONS
{education}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚡ STRATEGIC COMPETENCIES
{skills}

Executive Resume Template • {currentDate}"""
    else:  # professional template
        return f"""{name}
{'=' * len(name)}

📧 Email: {email}
📱 Phone: {phone}
📅 Generated: {currentDate}

🎯 CAREER OBJECTIVE
{objective}

🎓 EDUCATION
{education}

💼 WORK EXPERIENCE
{experience}

🛠️ SKILLS
{skills}

---
Generated by Professional Resume Builder
{currentDate}"""

@app.route("/")
def home():
    return "AI Resume Backend with Firebase Realtime Database is running"

@app.route("/generate_resume", methods=["POST"])
def generate_resume():
    data = request.json
    
    # Sanitize input
    name = data.get("name", "").strip()
    email = data.get("email", "").strip()
    phone = data.get("phone", "").strip()
    education = data.get("education", "").strip()
    experience = data.get("experience", "").strip()
    skills = data.get("skills", "").strip()
    objective = data.get("objective", "").strip()
    template = data.get("template", "professional")
    
    # Generate resume text based on template
    resume_text = generate_resume_text(data, template)
    
    # Create resume data
    resume_id = str(uuid.uuid4())
    resume_data = {
        "id": resume_id,
        "name": name,
        "email": email,
        "phone": phone,
        "education": education,
        "experience": experience,
        "skills": skills,
        "objective": objective,
        "template": template,
        "resume_text": resume_text,
        "created_at": datetime.utcnow().isoformat()
    }
    
    # Save to local database (for demo)
    resumes_db[resume_id] = resume_data
    
    # TODO: Save to Firebase Realtime Database
    # You can use Firebase REST API like this:
    # import requests
    # firebase_url = f"{FIREBASE_RTDB_URL}/resumes/{resume_id}.json"
    # response = requests.put(firebase_url, json=resume_data)
    
    return jsonify({
        "success": True,
        "resume_id": resume_id,
        "resume_text": resume_text
    })

@app.route("/resumes", methods=["GET"])
def get_all_resumes():
    # Return from local database (for demo)
    resumes = list(resumes_db.values())
    resumes.sort(key=lambda x: x.get('created_at', ''), reverse=True)
    return jsonify({"resumes": resumes})

@app.route("/resumes/<resume_id>", methods=["GET"])
def get_resume(resume_id):
    resume_data = resumes_db.get(resume_id)
    if resume_data:
        return jsonify({"resume": resume_data})
    else:
        return jsonify({"error": "Resume not found"}), 404

@app.route("/resumes/<resume_id>", methods=["DELETE"])
def delete_resume(resume_id):
    if resume_id in resumes_db:
        del resumes_db[resume_id]
        return jsonify({"success": True, "message": "Resume deleted successfully!"})
    else:
        return jsonify({"error": "Resume not found"}), 404

@app.route("/chatbot", methods=["POST"])
def chatbot():
    try:
        data = request.json
        user_message = data.get("message", "").strip().lower()
        
        if not user_message:
            return jsonify({"error": "Message is required"}), 400
        
        # Generate response based on keywords
        if 'resume' in user_message or 'cv' in user_message:
            response = "I can help you create a professional resume! Fill out the form with your details and click 'Generate Resume'. You can choose from Professional, Modern, or Executive templates."
        elif 'template' in user_message:
            response = "We offer three professional templates:\n\n💼 **Professional**: Classic design for corporate positions\n🎯 **Modern**: Contemporary style for creative roles\n🚀 **Executive**: Sophisticated layout for leadership positions\n\nClick on any template to select it!"
        elif 'download' in user_message or 'pdf' in user_message:
            response = "Once you generate your resume, a download button will appear below the preview. Click 'Download Resume as PDF' to get a professional PDF file!"
        elif 'help' in user_message or 'how' in user_message:
            response = "I'm here to help with resume building! Here's what I can assist with:\n\n📝 Resume writing tips\n📋 Template selection\n💼 Content suggestions\n📥 Download guidance\n✨ Formatting advice\n\nWhat would you like help with?"
        else:
            response = "I'm here to help with resume building! Ask me about:\n• Resume templates\n• Writing tips for each section\n• Downloading your PDF\n• Best practices\n\nWhat would you like to know?"
        
        return jsonify({
            "response": response,
            "status": "success"
        })
        
    except Exception as e:
        print(f"Error in chatbot: {e}")
        fallback_responses = [
            "I'm here to help with your resume building! Feel free to ask me about career advice, skill recommendations, or resume tips.",
            "As your AI resume assistant, I can help you create better resumes and provide career guidance. What would you like to know?",
            "I'm designed to help you build professional resumes and provide career insights. How can I assist you today?"
        ]
        
        import random
        return jsonify({
            "response": random.choice(fallback_responses),
            "status": "fallback"
        })

if __name__ == "__main__":
    print("🚀 Starting AI Resume Builder Backend")
    print("📡 Server running on: http://127.0.0.1:5000")
    print("🔗 Firebase RTDB URL:", FIREBASE_RTDB_URL)
    print("✅ Ready to accept requests!")
    app.run(debug=True, host="0.0.0.0", port=5000)
